apiVersion: skaffold/v3
kind: Config
metadata:
  name: chatbot
build:
  local:
    # We do not want to push the images to a registry especially during local development
    push: false
  artifacts:
    - image: devmadou/chatbot-api
      context: api  # The context is the directory where the Dockerfile is located
      docker:
        dockerfile: Dockerfile
      sync:
        infer: [ "**/*" ]   # All files are synced without triggering an image build on modification
    - image: devmadou/chatbot-web
      context: web
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          # We'll be more specific since we do not want to sync the node_modules directory
          - src/**/*
          - public/**/*

manifests:
  rawYaml:
    - k8s/api.yml
    - k8s/web.yml
    - k8s/app-ingress.yml